spring:
  application:
    name: petManager
  # 数据库：
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/petdb?serverTimezone=GMT
      username: root
      password: '050325'
      druid:
        #druid 数据源专有配置
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 6000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true

        #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
        #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
        #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # spring mvc逻辑视图映射
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    # 静态资源文件映射
    static-path-pattern: /static/**
  web:
    resources:
      # 配置静态资源所在路径
      static-locations: classpath:/static/

# 配置mybatis
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:/mappers/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.yanqi.petmanager.pojo

# 指定端口
server:
  port: 8080
logging:
  config: classpath:log4j2.xml

